### ISSUE TITLE
Methods should be separated by api types

### ISSUE THREAD

**Issue by emre** [steemdocs/steemdocs#31]
## Feature request

Example method: https://steemdocs.net/platform/methods/find_rc_accounts.html

With the Appbase release (0.19.10 and greater) there are multiple api types living in the Steem codebase.

- condenser_api
- rc_api
- witness_api

etc. We should group each API type and their supported methods.

#### What problem does this feature solve?

It will be organized better. If I want to see RC related methods, I can just skim through the RC API.

#### What does the proposed API look like?

[Steem Devportal](https://developers.steem.io/apidefinitions/#apidefinitions-condenser-api) separates the methods and API types)

#### How should this be implemented in your opinion?

A new directory structure on API methods

#### Are you willing to work on this yourself?**

I can work on this.

**Comment by kareniel** [comment]
Hi @emre ! Thanks for your suggestion.

There's actually already a notion for that on SDN, it's the "plugin" category in the platform section ("Plugin" refering to appbase plugins). It might not have seemed like it because there isn't much content yet, you can see an example of this for RC here: https://steemdocs.net/platform/plugins/rc.html

I'm planning on adding text descriptions for each section in the near future, maybe that will help resolve the ambiguity?

**Comment by emre** [comment]
I see.

Let's stick to the original plan, then. :)
